coredns_chart_version: 1.31.0
coredns_chart_download_url: https://github.com/coredns/helm/releases/download/coredns-{{ coredns_chart_version }}/coredns-{{ coredns_chart_version }}.tgz
coredns_chart_checksum: sha256:a057fed7108dd3e355b5bebeafe2d8b621a20e31e353da1996185ae8595058ff

coredns_chart_values:
  image:
    repository: coredns/coredns
    tag: ""
    pullPolicy: IfNotPresent
  replica_count: 1

coredns_namespace: kube-system
