- name: pki dir exists
  file:
    path: '{{ etcd__pki_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Keys are installed
  copy:
    src: '{{ item.dest }}'
    dest: '{{ etcd__pki_dir }}'
    owner: etcd
    group: etcd
    mode: 0600
  loop:
  - '{{ pki_tasks__fetch_etcd_ca_key }}'
  - '{{ pki_tasks__fetch_etcd_key }}'
  - '{{ pki_tasks__fetch_etcd_peer_key }}'

- name: Certificates are installed
  copy:
    src: '{{ item.dest }}'
    dest: '{{ etcd__pki_dir }}'
    owner: etcd
    group: etcd
    mode: 0644
  loop:
  - '{{ pki_tasks__fetch_etcd_ca_crt }}'
  - '{{ pki_tasks__fetch_etcd_crt }}'
  - '{{ pki_tasks__fetch_etcd_peer_crt }}'
