- name: User 'etcd'
  block:
  - name: Group "etcd" exists
    group:
      name: etcd
      gid: '{{ k8s__etcd_user_gid }}'
      system: True
      state: present
  - name: User 'etcd' exists
    user:
      name: etcd
      uid: '{{ k8s__etcd_user_uid }}'
      group: etcd
      create_home: False
      shell: /sbin/nologin
      system: True
      state: present
