- name: kube-apiserver is ready
  command: >-
    {{ k8s__k8s_bin_dir }}/kubectl get --raw='/readyz'
  register: _kube_apiserver_ready
  until: _kube_apiserver_ready.stdout == "ok"
  retries: 5
  delay: 5
  changed_when: false

- name: CoreDNS chart is downloaded
  get_url:
    url: '{{ coredns_chart_download_url }}'
    dest: '{{ k8s__remote_tmp_dir }}/coredns.tgz'
    checksum: '{{ coredns_chart_checksum }}'
- name: CoreDNS chart values.yml is rendered
  template:
    src: coredns_values.yml.j2
    dest: '{{ k8s__remote_tmp_dir }}/coredns_values.yml'
    owner: root
    group: root
    mode: 0600
- name: CoreDNS is deployed
  command: |
    {{ k8s__helm_bin_dir }}/helm install
    coredns
    -f {{ k8s__remote_tmp_dir }}/coredns_values.yml
    --version {{ coredns_chart_version }}
    --namespace {{ coredns_namespace }}
    {{ k8s__remote_tmp_dir }}/coredns.tgz
