- name: User 'kube-admin'
  block:
  - name: Group "kube-admin" exists
    group:
      name: kube-admin
      gid: '{{ k8s_master__kube_admin_user_gid }}'
      system: True
      state: present
  - name: User 'kube-admin' exists
    user:
      name: kube-admin
      uid: '{{ k8s_master__kube_admin_user_uid }}'
      group: kube-admin
      state: present
