apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coredns:psp:coredns
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
