apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:coredns
  namespace: kube-system
rules:
- apiGroups:
  - extensions
  resourceNames:
  - coredns
  resources:
  - podsecuritypolicies
  verbs:
  - use
