apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  hostIPC: true
  hostPID: true
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  volumes:
  - "*"
  fsGroup:
    rule: "RunAsAny"
  runAsUser:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "RunAsAny"
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - "*"
  seLinux:
    rule: "RunAsAny"
